foreground = yes
client = yes

[binance_fix]
accept = 127.0.0.1:19000
connect = fix-oe.testnet.binance.vision:9000

verifyChain = yes
CAfile = ./ca-certificates.crt
sni = fix-oe.testnet.binance.vision
